import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/context/AuthProvider";
import RadixThemeProvider from "@/components/providers/RadixThemeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <RadixThemeProvider>
          <AuthProvider>{children}</AuthProvider>
        </RadixThemeProvider>
      </body>
    </html>
  );
}
